# Generated by Django 5.0.1 on 2024-01-18 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cpost', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_post',
            old_name='name',
            new_name='user',
        ),
    ]
